name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: curl -fsSL https://rustwasm.github.io/wasm-pack/installer/init.sh | sh

      - name: Build Rust wasm
        run: wasm-pack build --target web --release
        working-directory: www

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: www/pnpm-lock.yaml
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Install dependencies
        run: pnpm install
        working-directory: www

      - name: Build frontend
        run: pnpm build
        working-directory: www
        env:
          BASE: /
